#!/system/bin/sh
sleep 30
#Max freq
echo 1300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
#Min freq
echo 51000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
#User Cap
echo 1300000 > /sys/module/cpu_tegra/parameters/cpu_user_cap
#Governor
echo smartmax > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#I/O Scheduler
echo deadline > /sys/block/mmcblk0/queue/scheduler
#Smartdimmer
echo 1 > /sys/devices/tegradc.0/smartdimmer/enable
#Smartdimmer aggressiveness
#LP_OC
echo 0 > /sys/module/cpu_tegra/parameters/enable_lp_oc
#
#MAX-CPU
echo 4 > /sys/kernel/tegra_mpdecision/conf/max_cpus


